name: CustomFlags
version: 1.0
main: me.becja10.CustomFlags.CustomFlags
depend: [WorldGuard]
description: allows adding custom flags to regions
commands:
  loadflags:
    description: load up any changes to the flag file
    usage: /loadflags
  